#version: '3.8'
#services:
#  product-service:
#    image: product-service:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://devuser:password@mongodb:27017/productdb
#    depends_on:
#      - mongodb
#
#  mongodb:
#    image: mongo:4.0.4
#    container_name: mongodb
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongodb_data:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=devuser
#      - MONGO_INITDB_ROOT_PASSWORD=password
#      - MONGO_INITDB_DATABASE=productdb
#    restart: always
#
#volumes:
#  mongodb_data: